AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SupportDesk API - Lambda + API Gateway + DynamoDB

Globals:
  Function:
    Timeout: 30
    MemorySize: 256
    Runtime: provided.al2023
    Architectures:
      - x86_64
    Environment:
      Variables:
        JWT_SECRET: !Ref JWTSecret
        FRONTEND_URL: !Ref FrontendURL
        USERS_TABLE: !Ref UsersTable
        ORGS_TABLE: !Ref OrgsTable
        TICKETS_TABLE: !Ref TicketsTable
        MESSAGES_TABLE: !Ref MessagesTable
        TIME_ENTRIES_TABLE: !Ref TimeEntriesTable
        CONVERSION_REQUESTS_TABLE: !Ref ConversionRequestsTable
        INVOICES_TABLE: !Ref InvoicesTable
        ACTIVITIES_TABLE: !Ref ActivitiesTable

Parameters:
  JWTSecret:
    Type: String
    NoEcho: true
    Default: change-me-in-production-to-a-long-random-string
  FrontendURL:
    Type: String
    Default: '*'
    Description: Frontend URL for CORS (e.g., https://supportfix.ai - no trailing slash)

Resources:
  SupportDeskApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: prod
      CorsConfiguration:
        AllowOrigins:
          - !Ref FrontendURL
        AllowCredentials: true
        AllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        AllowHeaders:
          - Content-Type
          - Authorization
        MaxAge: 300

  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bootstrap
      CodeUri: ../
      Events:
        CatchAll:
          Type: HttpApi
          Properties:
            ApiId: !Ref SupportDeskApi
            Path: /{proxy+}
            Method: ANY
      Policies:
        - DynamoDBCrudPolicy:
            TableName: supportdesk-users
        - DynamoDBCrudPolicy:
            TableName: supportdesk-organizations
        - DynamoDBCrudPolicy:
            TableName: supportdesk-tickets
        - DynamoDBCrudPolicy:
            TableName: supportdesk-messages
        - DynamoDBCrudPolicy:
            TableName: supportdesk-time-entries
        - DynamoDBCrudPolicy:
            TableName: supportdesk-conversion-requests
        - DynamoDBCrudPolicy:
            TableName: supportdesk-invoices
        - DynamoDBCrudPolicy:
            TableName: supportdesk-activities
    Metadata:
      BuildMethod: makefile

  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: supportdesk-users
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: email-index
          KeySchema:
            - AttributeName: email
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  OrgsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: supportdesk-organizations
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH

  TicketsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: supportdesk-tickets
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: organization_id
          AttributeType: S
        - AttributeName: created_at
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: org-created-index
          KeySchema:
            - AttributeName: organization_id
              KeyType: HASH
            - AttributeName: created_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  MessagesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: supportdesk-messages
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: ticket_id
          AttributeType: S
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: ticket_id
          KeyType: HASH
        - AttributeName: id
          KeyType: RANGE

  TimeEntriesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: supportdesk-time-entries
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: ticket_id
          AttributeType: S
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: ticket_id
          KeyType: HASH
        - AttributeName: id
          KeyType: RANGE

  ConversionRequestsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: supportdesk-conversion-requests
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: ticket_id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: ticket-id-index
          KeySchema:
            - AttributeName: ticket_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  InvoicesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: supportdesk-invoices
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: organization_id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: org-index
          KeySchema:
            - AttributeName: organization_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  ActivitiesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: supportdesk-activities
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${SupportDeskApi}.execute-api.${AWS::Region}.amazonaws.com/prod"
  FunctionArn:
    Description: Lambda Function ARN
    Value: !GetAtt ApiFunction.Arn
